version: '3.4'

services:
  agent:
    image: "gcr.io/datadoghq/agent:7.34.0"
    container_name: agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=env:lab source:docker project:workshop role:application
      - DD_LOG_LEVEL=OFF
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TRACE_METHODS=Worker.Service.Worker[DoWork]
    ports:
      - "8126:8126"
      - "8125:8125"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/datadog:/var/run/datadog

  worker-service:
    build: ./Worker.Service
    depends_on:
      - agent
    container_name: worker-service
    ports:
      - 5001:80
      - 9090:9090
    labels:
      com.datadoghq.ad.logs: >-
        [{
          "source": "csharp"
        }]
      squad: customer
      tribe: workers
      com.datadoghq.tags.service: worker-service
      com.datadoghq.tags.env: lab
      com.datadoghq.tags.version: 1.2
    environment:
      - DD_LOGS_INJECTION=true
      - DD_AGENT_HOST=agent
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_SERVICE=worker-service
      - DD_VERSION=1.2
      - DD_TRACE_METHODS=Worker.Service.Worker[DoWork]
    volumes:
      - /var/run/datadog:/var/run/datadog:ro
      - ./logs/:/var/log/datadog/dotnet/
